version: '3.8'
services:

  schedd:
    image: "htcondor/cm:8.9.6-el7"
    environment:
      USE_POOL_PASSWORD: "yes"
    configs:
    - source: pool_password
      target: /root/secrets/pool_password

  worker:
    image: "htcondor/execute:8.9.6-el7"
    deploy:
      replicas: 2
    environment:
      CONDOR_HOST: "schedd"
      USE_POOL_PASSWORD: "yes"
    configs:
    - source: pool_password
      target: /root/secrets/pool_password

  submit:
    image: "htcondor/submit:8.9.6-el7"
    environment:
      CONDOR_HOST: "schedd"
      USE_POOL_PASSWORD: "yes"
    configs:
    - source: pool_password
      target: /root/secrets/pool_password
    - source: test
      target: /home/submituser/test.sub

configs:
  pool_password:
    file: ./pool_password
  test:
    file: ./test.sub
