{{- if .Values.cm.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: htcondor-cm
  labels:
  {{- include "mini-htcondor.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
    {{- include "mini-htcondor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
      {{- include "mini-htcondor.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
      {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      - name: htc-vol
        configMap:
          name: htc-config
      containers:
      - name: schedd
        securityContext:
        {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.images.cm.image }}:{{ .Values.images.cm.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.images.pullPolicy }}
        env:
        - name: USE_POOL_PASSWORD
          value: "yes"
        ports:
        - name: cm
          containerPort: {{ .Values.images.cm.port }}
          protocol: TCP
        volumeMounts:
        - mountPath: /root/secrets/pool_password
          subPath: pool_password
          name: htc-vol
        resources:
        {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
