apiVersion: v1
kind: Service
metadata:
  name: schedd
  labels:
  {{- include "mini-htcondor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.images.cm.type }}
  ports:
  - port: {{ .Values.images.cm.port }}
    targetPort: cm
    protocol: TCP
    name: cm
  selector:
  {{- include "mini-htcondor.selectorLabels" . | nindent 4 }}
